language: r
cache: packages
sudo: required
warnings_are_errors: false

os:
  - linux
  - osx

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=False
  - R_LIBS="http://cran.rstudio.com"
  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
  - R_CHECK_ARGS="--no-build-vignettes --no-manual"
  - BOOTSTRAP_LATEX=""

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

r_github_packages:
  - dgrtwo/stackr
  - jimhester/covr

r_binary_install:
  - magrittr
  - dplyr
  - XML
  - jsonlite
  - httr

after_success:
  - Rscript -e 'library(covr); codecov()'
